100-hours-a-week/8-team-kar98-luckeat-be

.github/workflows/build-test.yml
commit시 자동으로  ./gradlew spotlessApply 수행하도록 수정
- Resolves #[이슈 번호]
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
=> Add Spotless formatting step to Build & Test workflow

src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java
카테고리 관련 API MVC 작성
- Resolves #[이슈 번호]
Closes #28 
Closes #29 
Closes #31 
Closes #33 
1. [변경 내용 1]
2. [변경 내용 2]
3. [변경 내용 3]
1. [테스트 1]
2. [테스트 2]
3. [테스트 3]
에러 관련 코드는 아직 만들어지지 않아서 추후에 업데이트 예정입니다
=> 카테고리 관련 API MVC 작성

.github/workflows/build-test.yml
yml trigger 및 오타 수정,
build-test.yml 에서 Apply spotless 부분을 제거하였습니다.
- closes #52 
1. checkstyle.yml 수정
=> refactor: Remove Apply spotless in CI workflow

src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java, src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java, src/main/java/com/luckeat/luckeatbackend/category/service/CategoryService.java, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
이 풀 리퀘스트는 예외 처리를 강화하고, 검증 로직을 추가하며, 보안 설정을 업데이트하기 위해 여러 변경 사항을 포함하고 있습니다. 주요 변경 사항은 커스텀 예외 추가, 검증 로직 강화, 보안 설정 업데이트입니다.
- closes #54
예외 처리 및 검증 로직 개선:
•	커스텀 예외 추가 및 예외 처리 로직 강화:
•	CategoryInvalidImageException, CategoryInvalidNameException, CategoryNameDuplicateException, CategoryNotFoundException을 추가하여 보다 세밀한 예외 처리가 가능하도록 개선했습니다.
•	검증 오류 발생 시 로깅을 추가하여 디버깅이 용이하도록 했습니다.
•	카테고리 이름 및 이미지 검증 로직 추가:
•	카테고리 이름과 이미지에 대한 검증을 강화하여 유효하지 않은 데이터가 저장되지 않도록 했습니다.
•	중복된 카테고리 이름을 방지하기 위한 검증 로직을 추가했습니다.
저장소 업데이트:
•	카테고리 중복 확인 및 삭제되지 않은 카테고리 조회 기능 추가
•	기존 카테고리 이름이 존재하는지 확인하는 기능을 추가했습니다.
•	삭제되지 않은 카테고리를 찾을 수 있도록 조회 로직을 개선했습니다.
보안 설정 업데이트:
•	카테고리 관련 요청에 대한 접근 권한 변경
•	카테고리 조회(GET) 요청은 인증 없이 접근할 수 있도록 허용했습니다.
•	그 외 카테고리 관련 요청은 인증이 필요하도록 설정을 변경했습니다.
=> 54 feature add jwt and errorcode at category domain edwin

src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
=> store 객체 미참조 오류 해결

src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
=> 모든 경로 CORS 허용

src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
=> StoreService 에러코드 추가

src/main/java/com/luckeat/luckeatbackend/review/controller/ReviewController.java, src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java, src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewUpdateDto.java, src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java, src/main/java/com/luckeat/luckeatbackend/users/model/User.java
리뷰 관련 예외 처리 개선 및 유저 모델 수정
- Closes #76 
- Resolves #[이슈 번호]
1. 리뷰 api 에러코드 개선
2. 유저모델 수정
포스트맨으로 테스트
=> 리뷰 관련 예외 처리 개선 

src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductUnauthenticatedException.java, src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductStatusRequestDto.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ValidDiscountPrice.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ValidDiscountPriceValidator.java, src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
- ProductUnauthenticatedException 추가: 인증되지 않은 사용자 접근 처리
- 상품 관리 작업 시 가게 소유자 검증 로직 추가
- 데이터 유효성 검사
- 응답 형식을 엔티티에서 DTO로 변경 (ProductResponseDto 사용)
- 상품 상태 변경 API를 PATCH 메서드로 변경하여 REST 원칙 준수
- 가게별 상품 조회 메서드 추가 (findByIdAndStore)
- Closes [#13]
- Closes [#15]
- Closes [#18]
- Closes [#19]
- Closes [#20]
1.  1번유저(1번가게의 주인)의 jwt토큰으로 1번 유저의 가게 상품등록
2. 1번유저(1번가게의 주인)의 jwt토큰으로 2번 유저의 가게 상품등록
1. 1번유저(1번가게의 주인)의 jwt토큰으로 1번 유저의 가게 상품 수정
1. 1번유저(1번가게의 주인)의 jwt토큰으로 2번 유저의 가게 상품 수정
=> [Product] API 개선 및 예외처리, 유효성 검사 추가

build.gradle, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java, src/main/java/com/luckeat/luckeatbackend/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/luckeat/luckeatbackend/users/controller/UserController.java, src/main/java/com/luckeat/luckeatbackend/users/model/JwtBlacklist.java, src/main/java/com/luckeat/luckeatbackend/users/repository/JwtBlacklistRepository.java, src/main/java/com/luckeat/luckeatbackend/users/service/JwtBlacklistService.java, src/test/java/com/luckeat/luckeatbackend/LuckeatApplicationTests.java
feat: JWT 블랙리스트 기능 추가 및 로그아웃 API 구현
- Closes #84
1. jwt 인증 수정 및 로그아웃 기능 구현
스웨거로 테스트
=> feat: JWT 블랙리스트 기능 추가 및 로그아웃 API 구현

src/main/java/com/luckeat/luckeatbackend/review/model/Review.java, src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
feat: 리뷰와 가게 간의 관계 설정 및 가게 상세 응답에 리뷰 목록 추가
1. 가게상세 조회시 리뷰도 볼수있게 추가
2. [변경 내용 2]
3. [변경 내용 3]
스웨거로 테스트
=> 리뷰와 가게 간의 관계 설정 및 가게 상세 응답에 리뷰 목록 추가

src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java, src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java, src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
리뷰 생성 및 수정 시 가게 평균 평점 업데이트 기능 추가, 가게 테이블 평균 별점 컬럼 추가
- Closes #87 
1. 가게 테이블평균 별점 컬럼 추가 
2. 가게 응답 코드에 평균 별점 추가
3. 리뷰 생성 및 수정 및 삭제시 가게 별점 반영
스웨거로 테스트
=> 리뷰 생성 및 수정 시 가게 평균 평점 업데이트 기능 추가, 가게 테이블 평균 별점 컬럼 추가

src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
가게 응답 DTO에 리뷰 갯수 카운트 추가
- Closes #95 
1. 모든 가게 응답 DTO에 리뷰 갯수를 알수있게 추가
스웨거로 확인
=> 모든 가게 응답 DTO에 리뷰 갯수 카운트 추가

src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
This pull request involves the removal of the feature to increment the share count of a store from the `StoreController` and `StoreService` classes. The most important changes include the deletion of the `incrementShareCount` method and its associated API endpoint.
- Closes #108 
Removal of share count increment feature:
* [`src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java`](diffhunk://#diff-4b03666a86b32c98983e5bf23cf7eec9bff90a4b64d63b34829e748e755a268eL157-L174): Removed the `incrementShareCount` method and its associated API endpoint, which was responsible for increasing the share count of a store.
* [`src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java`](diffhunk://#diff-1942bbb419a09cc09aff9dbba53ee52f2054639150d715cd190797e7243bf7e6 …
=> chore: 가게 공유 횟수 증가 기능 및 관련 메서드 삭제

src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
StoreRequestDto에 리뷰 요약, 평균 별점, 구글 장소 ID 필드 추가 및 유효성 검사 수정
- Closes #111 
StoreRequestDto에 리뷰 요약, 평균 별점, 구글 장소 ID 필드 추가 및 유효성 검사 수정
스웨거로 테스트
=> StoreRequestDto에 리뷰 요약, 평균 별점, 구글 장소 ID 필드 추가 및 유효성 검사 수정

src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java, src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
This pull request includes several changes to the `ShortUrlController` and `ShortUrlService` classes to add logging functionality and correct the URL format.
- Resolves #119
The most important changes are listed below:
Logging functionality added to `ShortUrlController`:
* [`src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java`](diffhunk://#diff-d62dcd02cdaf68cdc9115f7994af159da6684bc104df388dae4f0f5fa87511eeR3-R6): Imported `LocalDateTime` and `HttpServletRequest` to log user request information.
* [`src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java`](diffhunk://#diff-d62dcd02cdaf68cdc9115f7994af159da6684bc104df388dae4f0f5fa87511eeL26-R46): Modified the `redirectToOriginal` method to log user information such as IP …
=> feat: ShortUrlController에 사용자 요청 정보 로깅 기능 추가 및 ShortUrlService의 반환 URL 수정

src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
유효성 검사 수정
- Closes #118 
가게 정보 요청시 유효성 검사 수정
스웨거로 테스트
=> 가게 정보 요청시 유효성 검사 수정

src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java, src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
This pull request includes changes to the `ShortUrlController` and `ShortUrlService` classes to improve the URL redirection functionality and correct the URL path.
- Resolves #124 
* [`src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java`](diffhunk://#diff-d62dcd02cdaf68cdc9115f7994af159da6684bc104df388dae4f0f5fa87511eeL5-R18): Modified the `@RestController` annotation to specify the base path as `/s`.
* [`src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java`](diffhunk://#diff-35ca5312327a1a592704ac02b143ede40979fbc202678811930c531445a2813cL26-R30): Changed the return URL in the `getOriginalUrl` method to use the store ID instead of the hash code, ensuring the URL path is `/store/{storeId}`.### Description
=> fix: ShortUrlController의 경로 수정 및 ShortUrlService의 반환 URL 형식 변경

.gitignore, build.gradle, src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java, src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorResponse.java, src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java, src/main/java/com/luckeat/luckeatbackend/config/AwsS3Config.java
[AWS S3 이미지 업로드 기능 추가]
- S3 클라이언트를 이용하여 상품, 가게, 리뷰 이미지를 업로드할 수 있는 기능을 구현했습니다.
- 이미지 업로드 전용 API 엔드포인트 제공
- 각 도메인별 이미지 파일 관리 (products, stores, reviews)
- 이미지 업로드 후 URL 반환 시스템
- Resolves #126 
curl을 통해 테스트 했습니다.
=> feat: 이미지 업로드 구현(S3)

src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
securityConfig /s/** 경로 허용 수정
- Closes #127
=> securityConfig /s/** 경로 허용 수정

.gitignore, build.gradle, src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java, src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorResponse.java, src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java, src/main/java/com/luckeat/luckeatbackend/config/AwsS3Config.java, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java, src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java, src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
This pull request introduces several new features and improvements, mainly focusing on image upload functionality, error handling, and AWS S3 configuration. The most important changes include the addition of a new controller for image uploads, enhancements to the error response structure, and the implementation of a service for uploading images to AWS S3.
* [`src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java`](diffhunk://#diff-35e2f1a7f771e1bd1e8e893ce1be0d1f9af205c272a1e9dbd31a8565701b486cR1-R75): Added a new controller for handling image uploads to S3 with endpoints for product, store, and review images.
* [`src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java`](diffhunk://#diff-92a7d9abdf011cdcc691f2f1a0f72dd3bf9fd600c8e0ca4196 …
=> feat: image upload functionality, error handling, and AWS S3 configuration.

src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
getAllProducts 메서드에서 삭제된 제품을 제외하도록 수정
- Closes #136 
1. ProductService에서 getAllProduct에서 findByStore -> findByStoreAndDeletedAtIsNull 메서드로 수정
스웨거로 테스트
=> getAllProducts 메서드에서 삭제된 제품을 제외하도록 수정

src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductCountRequestDto.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java, src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java, src/main/java/com/luckeat/luckeatbackend/review/model/Review.java, src/main/java/com/luckeat/luckeatbackend/store/dto/ProductResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
상품 관련 DTO 및 서비스 수정: 상품 수량 및 설명 필드 추가, 상품 상태 수정 메서드 이름 변경
- Closes #138 
상품 DB 수정
스웨거로 테스트
=> 상품 관련 DTO 및 서비스 수정: 상품 수량 및 설명 필드 추가, 상품 상태 수정 메서드 이름 변경

src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java, src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
리뷰 작성 권한 URL 필드 제거 및 관련 DTO 수정
- Closes #145 
1. 리뷰 작성 권한 URL 필드 제거
2. 리뷰 작성 권한  URL 관련 DTO 삭제
=> 리뷰 작성 권한 URL 필드 제거 및 관련 DTO 수정

src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
카테고리 API 접근 권한 수정 - GET 요청에 대해 모든 경로 허용
- Closes #147
1. 카테고리 API 접근 권한 수정 - GET 요청에 대해 모든 경로 허용
=> 카테고리 API 접근 권한 수정 - GET 요청에 대해 모든 경로 허용

src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java
MyStoreResponseDto에 픽업 가능 시간 필드 추가
- Closes #151
MyStoreResponseDto에 픽업 가능 시간 필드 추가
=> MyStoreResponseDto에 픽업 가능 시간 필드 추가

src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java, src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java, src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationResponseDto.java
- isOpen 컬럼추가 및 상태변경 api추가
- 예약 응답 DTO에 닉네임 추가
스웨거로 테스트 완료
=> feat: isOpen 부활 및 예약DTO에 닉네임 추가

src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
ProductRequestDto에 상품 판매 여부(isOpen) 필드 추가
- Closes #154 
ProductRequestDto에 상품 판매 여부(isOpen) 필드 추가
스웨거로 테스트
=> ProductRequestDto에 상품 판매 여부(isOpen) 필드 추가

src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
가게의 상품 중 판매 중인 상품 존재 여부 확인 기능 수정
- Closes #156 
가게의 상품 중 판매 중인 상품 존재 여부 확인 기능 수정
스웨거로 테스트
=> 가게의 상품 중 판매 중인 상품 존재 여부 확인 기능 수정

build.gradle, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Spring Boot Actuator 의존성 추가 및 API 접근 권한 설정
- Closes #158 
Spring Boot Actuator 의존성 추가 및 API 접근 권한 설정
=>  Spring Boot Actuator 의존성 추가 및 API 접근 권한 설정

src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
=>  헬스체크 api 추가

src/main/java/com/luckeat/luckeatbackend/users/dto/UserInfoResponseDto.java, src/main/java/com/luckeat/luckeatbackend/users/model/User.java
- user 앤터티 수정
- use 관련 응답 DTO에 추가
=> feat: user 아낀금액, 주문건수 컬럼추가

src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/reservation/controller/ReservationController.java, src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java, src/main/java/com/luckeat/luckeatbackend/users/dto/UserInfoResponseDto.java, src/main/java/com/luckeat/luckeatbackend/users/model/User.java
재고 관리 기능 추가 및 예외 처리 개선
- Closes #162 
1. 예약 생성 재고 감소
2. 손님 혹은 사장님 예약 취소시 재고 증가
3. 사장님이 컨펌하면 금액과 예약 건수를 유저에 추가
4. user totalOrderCount -> totalProductCount로 변경
스웨거로 테스트
=> 재고 관리 기능 추가 및 예외 처리 개선

src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
가게에 이미 등록된 상품 존재 여부 확인 기능 추가
- Closes #165
1. 가게에 이미 등록된 상품 존재 여부 확인 기능 추가
2. 가게당 상품 1개만 등록되도록 변경
스웨거로 테스트
=> 가게에 이미 등록된 상품 존재 여부 확인 기능 추가

src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java, src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
상품 생성 및 업데이트 메서드 이름 변경, 상품 업데이트 로직 추가
- Closes #167
1. 상품 업데이트, 생성 로직 분리
2.  prductRequestDTO 업데이트, 생성 로직 분리 
스웨거로 테스트
=> 상품 생성 및 업데이트 메서드 이름 변경, 상품 업데이트 로직 추가

src/main/java/com/luckeat/luckeatbackend/users/model/User.java
User 모델의 totalSavedMoney 및 totalProductCount 필드 초기값 설정
- Closes #169 
User 모델의 totalSavedMoney 및 totalProductCount 필드 초기값 설정
스웨거로 테스트
=> User 모델의 totalSavedMoney 및 totalProductCount 필드 초기값 설정

src/main/java/com/luckeat/luckeatbackend/product/model/Product.java, src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
럭키트 예약 완료후 재고가 0개이면 상품 isopen false로 처리하기
- Closes #171
럭키트 예약 완료후 재고가 0개이면 상품 isopen false로 처리하기
스웨거로 테스트
=> 럭키트 예약 완료후 재고가 0개이면 상품 isopen false로 처리하기

.github/workflows/build-test.yml, .github/workflows/deploy.yml, .gitignore, build.gradle
백엔드 모니터링을 위한 Sentry 설정을 추가했습니다. 
이를 통해 프로덕션/개발 환경에서 발생하는 오류를 실시간으로 추적하고 모니터링할 수 있습니다.
- Closes #175
1. Sentry 설정 추가
- `build.gradle`에 Sentry 플러그인 및 설정 추가
- `application.yml`에 Sentry DSN 및 환경 설정 추가
2. GitHub Actions 워크플로우 수정
- `build-test.yml`에 Sentry 릴리즈 생성 단계 추가
- 환경(production/development)별 Sentry 설정 추가
- Gradle 빌드 시 Sentry 인증 토큰 환경변수 설정
1. 로컬 환경 테스트
- Sentry 테스트 엔드포인트를 통한 예외 발생 및 캡처 확인
- Sentry 대시보드에서 오류 수집 확인
센트리 설정하느라고 dev `application.yml` 수정했습니다.
dev에 머지하고 깃헙액션 문제없으면 prod 도 수정예정입니다.
=> 175 devops 백엔드 모니터링 설정하기

.github/workflows/deploy.yml, build.gradle
Bucket4j 라이브러리 추가 및 버전 업데이트
- Resolves #178 
1.apilimit 추가
=> build: Bucket4j 라이브러리 추가 및 버전 업데이트

src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationResponseDto.java, src/main/java/com/luckeat/luckeatbackend/reservation/model/Reservation.java, src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java, src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
예약 관련 DTO 및 서비스에서 리뷰 작성 여부 필드를 삭제하고, 관련 로직을 제거함
- Closes #183 
예약 관련 DTO 및 서비스에서 리뷰 작성 여부 필드를 삭제하고, 관련 로직을 제거함
스웨거로 테스트
=> 예약 관련 DTO 및 서비스에서 리뷰 작성 여부 필드를 삭제하고, 관련 로직을 제거함

src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java, src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java, src/main/java/com/luckeat/luckeatbackend/review/model/Review.java, src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java, src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
예약 ID를 필수 필드로 추가하고, 리뷰 작성 시 예약 확인 로직을 개선하여 예약의 소유자 및 상태를 검증하도록 수정함
- Closes #186
1. 리뷰모델에 예약 id추가
2. 예약 상태에 따른 리뷰 작성할 수 있게 수정
스웨거로 테스트
=>  예약 ID를 필수 필드로 추가하고, 리뷰 작성 시 예약 확인 로직을 개선하여 예약의 소유자 및 상태를 검증하도록 수정함

src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java, src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
Reservation 엔티티와의 1:1 관계가 설정
reservation 필드 추가
가게명, 상품명, 총 가격, 상품 주문 개수 필드가 추가
fromEntity 메서드에서 예약 정보를 통해 관련 데이터를 조회하도록 구현
=> 리뷰 응답 DTO에 가게명, 상품명, 총 가격, 상품 주문 개수 필드를 추가

src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java
=> feat: 리뷰dto에 유저닉네임 추가

RATE_LIMIT_README.md, build.gradle, src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java, src/main/java/com/luckeat/luckeatbackend/common/filter/IpAttributeFilter.java, src/main/java/com/luckeat/luckeatbackend/common/filter/RateLimitFilter.java, src/main/java/com/luckeat/luckeatbackend/config/RateLimitConfig.java, src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java, test-rate-limit.sh
- build.gradle: Caffeine 캐시 의존성 추가 및 Bucket4j 라이브러리 활성화
- RATE_LIMIT_README.md: API Rate Limit 구현 가이드 문서 추가
- test-rate-limit.sh: Rate Limit 테스트 스크립트 추가
- IpAttributeFilter.java: 클라이언트 IP 주소를 요청 속성으로 설정하는 필터 구현
- RateLimitFilter.java: IP 주소 기반 요청 제한을 위한 필터 구현
- RateLimitConfig.java: API Rate Limit 설정 클래스 추가
- WebConfig.java: CORS 및 IP 속성 필터 등록 설정 추가
- SecurityConfig.java: JWT 인증 및 CORS 설정 개선
This pull request introduces a comprehensive API Rate Limiting system to enhance the stability and security of the application by limiting the number of requests from users based on their IP addresses. The key changes include the addition of new filters, configuration files, and documentation to support this feature.
- Resolves #178 
* [`RATE_LIMIT_README.md`](diffhunk://#diff-e0ac4bf6b68c8ba1fefc5fab4 …
=> API Rate Limit 기능 추가 및 관련 문서 작성

src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java, src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
상품 재고 감소 로직을 0에서 isOpen=false로 적용되게 개선
-Closes #195 
1. 상품 레포지토리 로직 수정
2. 상품서비스 로직 수정
스웨거로 테스트
=> 상품 재고 감소 로직을 개선

build.gradle, src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java, src/main/java/com/luckeat/luckeatbackend/common/filter/RequestLoggingFilter.java, src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java, src/main/resources/logback-spring.xml
This pull request introduces several significant changes to the `luckeatbackend` project, focusing on enhancing logging capabilities, adding request logging, and updating configurations. The most important changes include enabling caching, creating log directories, adding a request logging filter, updating allowed origins, and configuring logback for different environments.
- Resolves #198 
Enhancements to logging capabilities:
* [`src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java`](diffhunk://#diff-6a26753afa25cd353375e5899202ec0e939dace2590ae44ff596e563f3bcf4ddR5-R46): Enabled caching with `@EnableCaching` and added a method to create log directories at application startup.
* [`src/main/java/com/luckeat/luckeatbackend/common/filter/RequestLoggingFilter.java`](diffhunk://#d …
=> 메인 클래스 지정 및 로그 디렉토리 생성 기능 추가

src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java, src/main/java/com/luckeat/luckeatbackend/common/exception/base/CustomException.java, src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
This pull request includes several changes to improve logging, update CORS configuration, and remove redundant code. The most important changes include adding a new logger for API errors, expanding allowed headers in CORS configuration, and removing the CORS configuration from the security configuration.
- Resolves #[이슈 번호]
* [`src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java`](diffhunk://#diff-9a01560238fa27fd385ecf4eff41350143de79f800ad6d8bd2b16abb50e038c3R7-R8): Added `apiLogger` to log API errors for various exception handlers. [[1]](diffhunk://#diff-9a01560238fa27fd385ecf4eff41350143de79f800ad6d8bd2b16abb50e038c3R7-R8) [[2]](diffhunk://#diff-9a01560238fa27fd385ecf4eff41350143de79f800ad6d8bd2b16abb50e038c3R33-R70) …
=> 로그 개선 및 CORS 설정 업데이트

src/main/java/com/luckeat/luckeatbackend/users/dto/LoginRequestDto.java, src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java, src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
비밀번호 필드 설명 수정
- LoginRequestDto: Base64로 인코딩된 비밀번호로 설명 변경
- RegisterRequestDto: Base64로 인코딩된 비밀번호로 설명 변경
비밀번호 처리 로직 추가
- Base64로 인코딩된 비밀번호를 디코딩
- 소문자로 변환하여 정규화
- BCrypt로 암호화하여 저장
로그인 시
- Base64로 인코딩된 비밀번호를 디코딩
- 소문자로 변환하여 정규화
- 저장된 암호화된 비밀번호와 비교
=> feat: 비밀번호 필드의 설명을 Base64로 인코딩된 비밀번호로 수정, 소문자로 변환하여 검증하도록 수정

src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
- StoreController.java: 가게 목록 조회 메서드에 페이지 번호와 페이지 크기 파라미터 추가
- StoreRepository.java: 삭제되지 않은 가게를 페이지 단위로 조회하는 메서드 추가
- StoreService.java: 가게 목록 조회 로직을 페이지네이션을 지원하도록 수정
- Resolves #205
=> feat: 가게 목록 조회 API에 페이지네이션 기능 추가

src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java, src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java, src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
- CategoryRepository: 카테고리 이름으로 조회하는 메서드 추가
- StoreController: 가게 목록 조회 메서드에 카테고리 ID 파라미터 추가
- StoreRepository: 위치 기반 및 카테고리 필터링을 위한 네이티브 쿼리 추가
- StoreService: 위치 기반 및 카테고리 필터링 로직 통합
This pull request introduces several changes to improve the functionality and performance of the `StoreService` and related components. The most significant changes include adding new query methods for filtering and sorting stores, modifying the `StoreController` to support category-based filtering, and refactoring the `StoreService` to delegate filtering and sorting to the repository layer.
- Resolves #208 
Enhancements to store filtering and sorting:
* [`src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java`](diffhunk://#diff-5ccebb989ff7f0476cdad4a833fd74ccdd6e58e72e4af94a5d1e9aa107 …
=> feat(store): 가게 목록 조회 API에 카테고리 필터링 및 위치 기반 검색 기능 추가

src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java, src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/model/Store.java, src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
=> 출시를 위한 메인 머지

src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
This pull request includes changes to the `StoreRepository` and `StoreService` classes aimed at improving the sorting and filtering functionality for store data. The most important changes include adding new sorting criteria, removing unused imports, and simplifying the sorting logic in the service layer.
- Resolves #212 
* [`src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java`](diffhunk://#diff-5ccebb989ff7f0476cdad4a833fd74ccdd6e58e72e4af94a5d1e9aa107589c2dL45-R46): Added new sorting criteria for store ID and review count in the `findStoresWithLocation` and other query methods. [[1]](diffhunk://#diff-5ccebb989ff7f0476cdad4a833fd74ccdd6e58e72e4af94a5d1e9aa107589c2dL45-R46) [[2]](diffhunk://#diff-5ccebb989ff7f0476cdad4a833fd74ccdd6e58e72e4af94a5d1e9aa107589c2dL72 …
=> feat: 가게 목록 조회 API의 정렬 기준 및 쿼리 개선

src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java, src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
사용자 등록 요청 DTO에서 역할 필드를 문자열로 변경하고, 유효성 검사를 강화함.
- Closes #213
사용자 등록 요청 DTO에서 역할 필드를 문자열로 변경하고, 유효성 검사를 강화함.
스웨거로 테스트
=> 사용자 등록 요청 DTO에서 역할 필드를 문자열로 변경하고, 유효성 검사를 강화함.

.github/workflows/deploy.yml, Dockerfile
dockerfile 및 deploy 설정
- Closes #229 
1. dockerfile 생성
2. deploy.yml 도커를 실행하도록 수정
로컬에서 테스트
=> dockerfile, deploy.yml 수정

.github/workflows/deploy.yml
=>  deploy 수정

.github/workflows/deploy.yml
deploy.yml에서 AWS_REGION_SECRET 환경 변수 설정 위치 수정
=> deploy.yml에서 AWS_REGION_SECRET 환경 변수 설정 위치 수정

.github/workflows/deploy.yml
deploy.yml에서 AWS_REGION_SECRET 환경 변수 제거 및 ECR 로그인 방식 수정
=> deploy.yml에서 AWS_REGION_SECRET 환경 변수 제거 및 ECR 로그인 방식 수정

.github/workflows/deploy.yml
deploy.yml에서 Docker 이미지 빌드, 태그, 푸시 과정 개선 및 환경 변수 설정 추가
=>  deploy.yml에서 Docker 이미지 빌드, 태그, 푸시 과정 개선 및 환경 변수 설정 추가

.github/workflows/deploy.yml
deploy.yml에서 AWS 자격증명 파일 설정 추가 및 ECR 로그인 방식 개선
=> deploy.yml에서 AWS 자격증명 파일 설정 추가 및 ECR 로그인 방식 개선

.github/workflows/deploy.yml
deploy.yml에서 AWS_REGION_SECRET 및 AWS_SHARED_CREDENTIALS_FILE 환경변수 설정 추가
=>  deploy.yml에서 AWS_REGION_SECRET 및 AWS_SHARED_CREDENTIALS_FILE 환경변수 설정 추가

.github/workflows/deploy.yml
deploy.yml에서 환경 변수 설정 방식을 개선하여 가독성 향상
=> deploy.yml에서 환경 변수 설정 방식을 개선하여 가독성 향상

.github/workflows/deploy.yml
deploy.yml에서 AWS_REGION 환경 변수를 고정값으로 설정하고, 환경 변수 설정 방식을 간소화하여 가독성 향상
=> deploy.yml에서 AWS_REGION 환경 변수를 고정값으로 설정하고, 환경 변수 설정 방식을 간소화하여 가독성 향상

.github/workflows/deploy.yml
=>  bug deploy 수정

PROMETHEUS_GRAFANA_README.md, build.gradle, grafana/dashboards/loki-logs-dashboard.json, grafana/dashboards/mysql-overview-dashboard.json, grafana/provisioning/dashboards/dashboard.yml, grafana/provisioning/datasources/datasource.yml, loki-config.yml, prometheus.yml, promtail-config.yml, src/main/java/com/luckeat/luckeatbackend/common/controller/MetricsTestController.java, src/main/java/com/luckeat/luckeatbackend/common/interceptor/MetricsInterceptor.java, src/main/java/com/luckeat/luckeatbackend/config/MetricsConfig.java, src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java, src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
- build.gradle: Prometheus 및 Micrometer 의존성 추가
- loki-config.yml: Loki 설정 파일 추가
- prometheus.yml: Prometheus 설정 파일 추가
- promtail-config.yml: Promtail 설정 파일 추가
- Grafana 대시보드 및 데이터 소스 설정 파일 추가
- 메트릭 테스트를 위한 MetricsTestController 및 MetricsInterceptor 클래스 추가
- API 요청 시간을 측정하는 인터셉터 및 메트릭 설정 클래스 추가
- WebConfig에 메트릭 인터셉터 등록
- SecurityConfig에 메트릭 테스트 엔드포인트 허용 추가
This pull request introduces several new configurations and features related to monitoring and logging for the LuckEat application. The changes include new Grafana dashboards, Prometheus metrics, and Loki log aggregation. Additionally, a new metrics testing controller and interceptor have been added to the backend application.
- Resolves #223 
* Added a new Grafana dashboard for monitoring logs and error counts …
=> feat: Prometheus 및 Grafana 모니터링 시스템 설정 추가

src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java, src/main/java/com/luckeat/luckeatbackend/common/dto/PresignedUrlResponse.java, src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java
[주요 변경사항]
1. ImageUploadController.java
- 가게 및 리뷰 이미지 업로드를 위한 프리사인드 URL 생성 기능 추가
- API 엔드포인트 추가 및 관련 로직 구현
2. PresignedUrlResponse.java
- 프리사인드 URL과 파일 키를 포함하는 DTO 클래스 추가
- URL 생성 결과를 클라이언트에 전달하기 위한 구조 정의
3. S3UploadService.java
- S3 프리사인드 URL 생성 로직 구현
- S3Presigner를 사용하여 프리사인드 URL을 생성하고, 이미지 업로드를 위한 설정 추가
- 자격 증명 및 ACL 설정을 포함하여 S3 버킷과의 통신을 위한 로직 개선
- closes #227 
스웨거, s3에서 테스트 및 확인 완료
=> feat: 가게, 리뷰 이미지 업로드를 위한 프리사인드 URL 구현

.github/workflows/deploy-prod.yml
deploy-prod.yml 파일 추가: AWS EC2에 Docker 이미지를 배포하는 새로운 워크플로우 설정
prod용 deploy 추가
=>  deploy-prod.yml 파일 추가: AWS EC2에 Docker 이미지를 배포하는 새로운 워크플로우 설정

.github/workflows/deploy-prod.yml
=> Deploy-prod수정 main 머지

.github/workflows/deploy-prod.yml
운영 환경의 무중단 배포를 위해 deploy-prod.yml 워크플로우를 수정했습니다. ALB와 ASG를 활용하여 새로운 인스턴스가 완전히 준비된 후에 트래픽을 전환하는 방식으로 구현했습니다.
- Closes #255
1. ASG capacity 조정을 통한 무중단 배포 로직 구현
- 배포 시 ASG capacity를 2로 증가시켜 새 인스턴스 추가
- 새 인스턴스가 완전히 준비된 후 이전 인스턴스 제거
- 배포 완료 후 ASG 설정을 원래대로 복구
2. ALB 헬스 체크 모니터링 로직 추가
- 새 인스턴스의 ALB 타겟 그룹 헬스 체크 상태 모니터링
- 두 인스턴스 모두 healthy 상태일 때만 다음 단계 진행
3. 배포 실패 시 안전장치 구현
- 새 인스턴스 헬스 체크 실패 시 기존 운영 환경 보호
- GitHub Actions 워크플로우 실패 시 자동으로 문제 있는 인스턴스 제거
1. 로컬 환경에서 AWS CLI 명령어 테스트
- ASG 설정 변경 및 조회
- ALB 타겟 그룹 상태 확인
2. AWS 콘솔에서 필요한 권한 설정 확인
- IAM 사용자 권한
- EC2 인스턴스 프로파일
- GitHub Actions Secrets 설정
배포를 위해 다음 GitHub Secrets가 필요합니다:
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- ECR_REGISTRY
- PROD_ALB_TARGET_GROUP_ARN
또한 ASG의 시작 템플릿에 다음 설정이 필요합니다:
- 도커와 도커 컴포즈가 설치된 AMI
- ECR 접근 권한이 있는 인스턴스 프로파일
- 적절한 User …
=> feat: ALB, ASG를 이용한 무중단 배포 구현

.github/workflows/deploy-prod.yml
AWS ALB와 ASG를 활용한 무중단 배포 기능을 구현하고 개선했습니다. 
배포 과정에서 서비스 중단 없이 새로운 버전의 애플리케이션을 안전하게 배포할 수 있도록 하였습니다.
- Closes #255
1. 무중단 배포 기본 로직 구현
- ALB 헬스체크 및 ASG 인스턴스 관리 설정
- 배포 모니터링 로직 구현
- 롤백 안전장치 추가
2. 배포 안정성 강화
- MinHealthyPercentage를 50%에서 100%로 상향 조정
(최소 하나 이상의 인스턴스가 트래픽을 처리할수 있도록)
- ALB 헬스체크 상태 기반 배포 프로세스 개선
- 인스턴스 상태 전환 로직 명확화
3. 인스턴스 관리 로직 개선
- 새로운 인스턴스 보호 설정 추가
- 기존/신규 인스턴스 상태 확인 로직 개선
- 기존 인스턴스 종료 프로세스 안정화
1. 로컬 환경에서 AWS CLI 명령어 테스트
- ASG 용량 조정 및 인스턴스 상태 변경 검증
- ALB 타겟 그룹 헬스체크 동작 확인
2. GitHub Actions 워크플로우 테스트
- 배포 스크립트 실행 및 로그 확인
- 인스턴스 전환 과정 모니터링
- 무중단 여부 확인
3. 실제 환경 테스트
- 프로덕션 환경과 동일한 설정으로 테스트
- 다양한 시나리오에서의 배포 안정성 검증
1. ASG 설정
- 최소 용량: 1
- 최대 용량: 3
- 원하는 용량: 1
2. ALB 설정
- 타겟 그룹 헬스체크 설정 확인
- 인스턴스 등록/해제 지연 시간 고려
3. GitHub Secrets
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- …
=> asg, alb 를 통한 무중단배포 구현

src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java, src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
가게 목록 조회 API에 성능 테스트 기능을 추가하였습니다. 1000번의 API 호출을 통해 성능 지표(min, max, avg, p99)를 측정하고, DB 쿼리 실행 시간을 포함하여 결과를 반환하도록 수정하였습니다. 또한, 서비스 메소드에서 쿼리 실행 시간을 측정하는 로직을 개선하여 성능 모니터링을 강화하였습니다.
- Resolves #265
=> feat(store): 가게 목록 조회 성능 테스트 기능 추가 및 쿼리 실행 시간 측정 로직 개선

src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
fix(StoreController): `/performance-test` 엔드포인트 매핑 오류 수정
`/api/v1/stores/performance-test` 경로로 요청 시, Spring MVC는 이 경로를 `/{store_id}` 경로 변수를 사용하는 `getStoreDetailById` 메소드에 먼저 매핑하려고 시도했습니다. 이로 인해 문자열 "performance-test"를 Long 타입인 `storeId`로 변환하는 과정에서 `MethodArgumentTypeMismatchException` 예외가 발생했습니다.
`StoreController` 내에서 `@GetMapping("/performance-test")` 어노테이션이 붙은 `runStoreSearchPerformanceTest` 메소드를 `@GetMapping("/{store_id}")` 어노테이션이 붙은 `getStoreDetailById` 메소드보다 앞에 위치하도록 순서를 변경했습니다.
Spring MVC는 핸들러 메소드를 매핑할 때 더 구체적인 경로를 우선적으로 고려하므로, 이 변경을 통해 `/performance-test` 요청이 올바른 핸들러 메소드로 라우팅되도록 수정했습니다.
1.  애플리케이션을 실행합니다.
2.  `/api/v1/stores/performance-test` 엔드포인트로 GET 요청을 보내 정상적으로 성능 테스트 결과가 반환되는지 확인합니다.
3.  `/api/v1/stores/{유효한_가게_ID}` 엔드포인트로 GET 요청을 보내 가게 상세 정보가 정상적으로 반환되는지 확인합니다.
- Close …
=> fix(StoreController): `/performance-test` 엔드포인트 매핑 오류 수정

src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
fix(StoreController): `/performance-test` 엔드포인트 매핑 오류 수정
`/api/v1/stores/performance-test` 경로로 요청 시, Spring MVC는 이 경로를 `/{store_id}` 경로 변수를 사용하는 `getStoreDetailById` 메소드에 먼저 매핑하려고 시도했습니다. 이로 인해 문자열 "performance-test"를 Long 타입인 `storeId`로 변환하는 과정에서 `MethodArgumentTypeMismatchException` 예외가 발생했습니다.
Update performance test endpoint mapping
Spring MVC는 핸들러 메소드를 매핑할 때 더 구체적인 경로를 우선적으로 고려하므로, 이 변경을 통해 `test/performance-test` 요청이 올바른 핸들러 메소드로 라우팅되도록 수정했습니다.
1.  애플리케이션을 실행합니다.
2.  `/api/v1/stores/test/performance-test` 엔드포인트로 GET 요청을 보내 정상적으로 성능 테스트 결과가 반환되는지 확인합니다.
3.  `/api/v1/stores/{유효한_가게_ID}` 엔드포인트로 GET 요청을 보내 가게 상세 정보가 정상적으로 반환되는지 확인합니다.
- Close #issue_number (해당되는 경우)
=> fix(StoreController): Update performance test endpoint mapping
